# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/guiqt/ui/frontend.ui'
#
# Created: Sat May 21 15:12:47 2011
#      by: pyside-uic 0.2.8 running on PySide 1.0.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 500)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nav = QtGui.QWidget(self.centralwidget)
        self.nav.setStyleSheet("#nav{background:#202429 url(:/headerbar.png) no-repeat}\n"
"QLabel{color:rgba(255,255,255,51);font-size:10px}\n"
"QPushButton{border:none;background:none;font-weight:bold;color:#fff;padding:10px}\n"
"QPushButton:!enabled{color:#707070}\n"
"QPushButton:checked{color:#ff8000}\n"
"#nav_options,#nav_about{padding:0;height:14px;font-size:11px;font-weight:normal;color:#ccc}\n"
"#nav_options:checked,#nav_about:checked{color:#ff8000}")
        self.nav.setObjectName("nav")
        self.nav_layout = QtGui.QHBoxLayout(self.nav)
        self.nav_layout.setSpacing(10)
        self.nav_layout.setContentsMargins(0, 0, 0, 0)
        self.nav_layout.setObjectName("nav_layout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.nav_layout.addItem(spacerItem)
        self.nav_start = QtGui.QPushButton(self.nav)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_start.sizePolicy().hasHeightForWidth())
        self.nav_start.setSizePolicy(sizePolicy)
        self.nav_start.setCursor(QtCore.Qt.PointingHandCursor)
        self.nav_start.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nav_start.setCheckable(True)
        self.nav_start.setChecked(True)
        self.nav_start.setFlat(True)
        self.nav_start.setObjectName("nav_start")
        self.nav_layout.addWidget(self.nav_start)
        self.nav_arrow_1 = QtGui.QLabel(self.nav)
        self.nav_arrow_1.setObjectName("nav_arrow_1")
        self.nav_layout.addWidget(self.nav_arrow_1)
        self.nav_details = QtGui.QPushButton(self.nav)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_details.sizePolicy().hasHeightForWidth())
        self.nav_details.setSizePolicy(sizePolicy)
        self.nav_details.setCursor(QtCore.Qt.PointingHandCursor)
        self.nav_details.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nav_details.setCheckable(True)
        self.nav_details.setFlat(True)
        self.nav_details.setObjectName("nav_details")
        self.nav_layout.addWidget(self.nav_details)
        self.nav_arrow_2 = QtGui.QLabel(self.nav)
        self.nav_arrow_2.setObjectName("nav_arrow_2")
        self.nav_layout.addWidget(self.nav_arrow_2)
        self.nav_launcher = QtGui.QPushButton(self.nav)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_launcher.sizePolicy().hasHeightForWidth())
        self.nav_launcher.setSizePolicy(sizePolicy)
        self.nav_launcher.setCursor(QtCore.Qt.PointingHandCursor)
        self.nav_launcher.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nav_launcher.setCheckable(True)
        self.nav_launcher.setFlat(True)
        self.nav_launcher.setObjectName("nav_launcher")
        self.nav_layout.addWidget(self.nav_launcher)
        self.nav_arrow_3 = QtGui.QLabel(self.nav)
        self.nav_arrow_3.setObjectName("nav_arrow_3")
        self.nav_layout.addWidget(self.nav_arrow_3)
        self.nav_compact = QtGui.QPushButton(self.nav)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_compact.sizePolicy().hasHeightForWidth())
        self.nav_compact.setSizePolicy(sizePolicy)
        self.nav_compact.setCursor(QtCore.Qt.PointingHandCursor)
        self.nav_compact.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nav_compact.setCheckable(True)
        self.nav_compact.setFlat(True)
        self.nav_compact.setObjectName("nav_compact")
        self.nav_layout.addWidget(self.nav_compact)
        self.nav_arrow_4 = QtGui.QLabel(self.nav)
        self.nav_arrow_4.setObjectName("nav_arrow_4")
        self.nav_layout.addWidget(self.nav_arrow_4)
        self.nav_test = QtGui.QPushButton(self.nav)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_test.sizePolicy().hasHeightForWidth())
        self.nav_test.setSizePolicy(sizePolicy)
        self.nav_test.setCursor(QtCore.Qt.PointingHandCursor)
        self.nav_test.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nav_test.setCheckable(True)
        self.nav_test.setFlat(True)
        self.nav_test.setObjectName("nav_test")
        self.nav_layout.addWidget(self.nav_test)
        self.nav_arrow_5 = QtGui.QLabel(self.nav)
        self.nav_arrow_5.setObjectName("nav_arrow_5")
        self.nav_layout.addWidget(self.nav_arrow_5)
        self.nav_publish = QtGui.QPushButton(self.nav)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nav_publish.sizePolicy().hasHeightForWidth())
        self.nav_publish.setSizePolicy(sizePolicy)
        self.nav_publish.setCursor(QtCore.Qt.PointingHandCursor)
        self.nav_publish.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nav_publish.setCheckable(True)
        self.nav_publish.setFlat(True)
        self.nav_publish.setObjectName("nav_publish")
        self.nav_layout.addWidget(self.nav_publish)
        self.nav_smallbox = QtGui.QVBoxLayout()
        self.nav_smallbox.setSpacing(6)
        self.nav_smallbox.setContentsMargins(72, -1, -1, -1)
        self.nav_smallbox.setObjectName("nav_smallbox")
        self.nav_options = QtGui.QPushButton(self.nav)
        self.nav_options.setCursor(QtCore.Qt.PointingHandCursor)
        self.nav_options.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nav_options.setCheckable(True)
        self.nav_options.setFlat(True)
        self.nav_options.setObjectName("nav_options")
        self.nav_smallbox.addWidget(self.nav_options)
        self.nav_about = QtGui.QPushButton(self.nav)
        self.nav_about.setCursor(QtCore.Qt.PointingHandCursor)
        self.nav_about.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nav_about.setCheckable(True)
        self.nav_about.setFlat(True)
        self.nav_about.setObjectName("nav_about")
        self.nav_smallbox.addWidget(self.nav_about)
        self.nav_layout.addLayout(self.nav_smallbox)
        self.verticalLayout.addWidget(self.nav)
        self.pages = QtGui.QStackedWidget(self.centralwidget)
        self.pages.setObjectName("pages")
        self.page_start = QtGui.QWidget()
        self.page_start.setObjectName("page_start")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.page_start)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self._2 = QtGui.QVBoxLayout()
        self._2.setSpacing(40)
        self._2.setObjectName("_2")
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._2.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.page_start)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self._2.addWidget(self.label)
        self.groupBox = QtGui.QGroupBox(self.page_start)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.start_open_label = QtGui.QLabel(self.groupBox)
        self.start_open_label.setObjectName("start_open_label")
        self.horizontalLayout_2.addWidget(self.start_open_label)
        self.start_open_package = QtGui.QLineEdit(self.groupBox)
        self.start_open_package.setMinimumSize(QtCore.QSize(400, 0))
        self.start_open_package.setObjectName("start_open_package")
        self.horizontalLayout_2.addWidget(self.start_open_package)
        self.start_open_browse = QtGui.QPushButton(self.groupBox)
        self.start_open_browse.setObjectName("start_open_browse")
        self.horizontalLayout_2.addWidget(self.start_open_browse)
        self._2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.page_start)
        self.groupBox_2.setObjectName("groupBox_2")
        self.hboxlayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.hboxlayout.setObjectName("hboxlayout")
        self.start_create_label = QtGui.QLabel(self.groupBox_2)
        self.start_create_label.setObjectName("start_create_label")
        self.hboxlayout.addWidget(self.start_create_label)
        self.start_create_package = QtGui.QLineEdit(self.groupBox_2)
        self.start_create_package.setMinimumSize(QtCore.QSize(400, 0))
        self.start_create_package.setObjectName("start_create_package")
        self.hboxlayout.addWidget(self.start_create_package)
        self.start_create_browse = QtGui.QPushButton(self.groupBox_2)
        self.start_create_browse.setObjectName("start_create_browse")
        self.hboxlayout.addWidget(self.start_create_browse)
        self._2.addWidget(self.groupBox_2)
        spacerItem3 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._2.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self._2)
        spacerItem4 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.pages.addWidget(self.page_start)
        self.page_details = QtGui.QWidget()
        self.page_details.setObjectName("page_details")
        self.gridLayout = QtGui.QGridLayout(self.page_details)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DetailsGroupBox = QtGui.QGroupBox(self.page_details)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DetailsGroupBox.sizePolicy().hasHeightForWidth())
        self.DetailsGroupBox.setSizePolicy(sizePolicy)
        self.DetailsGroupBox.setObjectName("DetailsGroupBox")
        self.formLayout_4 = QtGui.QFormLayout(self.DetailsGroupBox)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.NameLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.NameLabel.setObjectName("NameLabel")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.NameLabel)
        self.Name = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Name.setMaxLength(128)
        self.Name.setObjectName("Name")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.Name)
        self.AppIDLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.AppIDLabel.setObjectName("AppIDLabel")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.AppIDLabel)
        self.AppID = QtGui.QLineEdit(self.DetailsGroupBox)
        self.AppID.setMaxLength(128)
        self.AppID.setObjectName("AppID")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.AppID)
        self.PublisherLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.PublisherLabel.setObjectName("PublisherLabel")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.PublisherLabel)
        self.Publisher = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Publisher.setMaxLength(128)
        self.Publisher.setObjectName("Publisher")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.Publisher)
        self.HomepageLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.HomepageLabel.setObjectName("HomepageLabel")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.HomepageLabel)
        self.Homepage = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Homepage.setMaxLength(128)
        self.Homepage.setObjectName("Homepage")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.Homepage)
        self.CategoryLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.CategoryLabel.setObjectName("CategoryLabel")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.CategoryLabel)
        self.Category = QtGui.QComboBox(self.DetailsGroupBox)
        self.Category.setObjectName("Category")
        self.Category.addItem("")
        self.Category.setItemText(0, "Accessibility")
        self.Category.addItem("")
        self.Category.setItemText(1, "Development")
        self.Category.addItem("")
        self.Category.setItemText(2, "Education")
        self.Category.addItem("")
        self.Category.setItemText(3, "Games")
        self.Category.addItem("")
        self.Category.setItemText(4, "Graphics & Pictures")
        self.Category.addItem("")
        self.Category.setItemText(5, "Internet")
        self.Category.addItem("")
        self.Category.setItemText(6, "Music & Video")
        self.Category.addItem("")
        self.Category.setItemText(7, "Office")
        self.Category.addItem("")
        self.Category.setItemText(8, "Security")
        self.Category.addItem("")
        self.Category.setItemText(9, "Utilities")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.Category)
        self.DescriptionLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.DescriptionLabel.setObjectName("DescriptionLabel")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.DescriptionLabel)
        self.Description = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Description.setMaxLength(512)
        self.Description.setObjectName("Description")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.Description)
        self.LanguageLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.LanguageLabel.setObjectName("LanguageLabel")
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.LanguageLabel)
        self.Language = QtGui.QComboBox(self.DetailsGroupBox)
        self.Language.setObjectName("Language")
        self.Language.addItem("")
        self.Language.setItemText(0, "Multilingual")
        self.Language.addItem("")
        self.Language.setItemText(1, "English")
        self.Language.addItem("")
        self.Language.setItemText(2, "Afrikaans")
        self.Language.addItem("")
        self.Language.setItemText(3, "Albanian")
        self.Language.addItem("")
        self.Language.setItemText(4, "Arabic")
        self.Language.addItem("")
        self.Language.setItemText(5, "Armenian")
        self.Language.addItem("")
        self.Language.setItemText(6, "Basque")
        self.Language.addItem("")
        self.Language.setItemText(7, "Belarusian")
        self.Language.addItem("")
        self.Language.setItemText(8, "Bosnian")
        self.Language.addItem("")
        self.Language.setItemText(9, "Breton")
        self.Language.addItem("")
        self.Language.setItemText(10, "Bulgarian")
        self.Language.addItem("")
        self.Language.setItemText(11, "Catalan")
        self.Language.addItem("")
        self.Language.setItemText(12, "Cibemba")
        self.Language.addItem("")
        self.Language.setItemText(13, "Croatian")
        self.Language.addItem("")
        self.Language.setItemText(14, "Czech")
        self.Language.addItem("")
        self.Language.setItemText(15, "Danish")
        self.Language.addItem("")
        self.Language.setItemText(16, "Dutch")
        self.Language.addItem("")
        self.Language.setItemText(17, "Efik")
        self.Language.addItem("")
        self.Language.setItemText(18, "Estonian")
        self.Language.addItem("")
        self.Language.setItemText(19, "Farsi")
        self.Language.addItem("")
        self.Language.setItemText(20, "Finnish")
        self.Language.addItem("")
        self.Language.setItemText(21, "French")
        self.Language.addItem("")
        self.Language.setItemText(22, "Galician")
        self.Language.addItem("")
        self.Language.setItemText(23, "Georgian")
        self.Language.addItem("")
        self.Language.setItemText(24, "German")
        self.Language.addItem("")
        self.Language.setItemText(25, "Greek")
        self.Language.addItem("")
        self.Language.setItemText(26, "Hebrew")
        self.Language.addItem("")
        self.Language.setItemText(27, "Hungarian")
        self.Language.addItem("")
        self.Language.setItemText(28, "Icelandic")
        self.Language.addItem("")
        self.Language.setItemText(29, "Igbo")
        self.Language.addItem("")
        self.Language.setItemText(30, "Indonesian")
        self.Language.addItem("")
        self.Language.setItemText(31, "Irish")
        self.Language.addItem("")
        self.Language.setItemText(32, "Italian")
        self.Language.addItem("")
        self.Language.setItemText(33, "Japanese")
        self.Language.addItem("")
        self.Language.setItemText(34, "Khmer")
        self.Language.addItem("")
        self.Language.setItemText(35, "Korean")
        self.Language.addItem("")
        self.Language.setItemText(36, "Kurdish")
        self.Language.addItem("")
        self.Language.setItemText(37, "Latvian")
        self.Language.addItem("")
        self.Language.setItemText(38, "Lithuanian")
        self.Language.addItem("")
        self.Language.setItemText(39, "Luxembourgish")
        self.Language.addItem("")
        self.Language.setItemText(40, "Macedonian")
        self.Language.addItem("")
        self.Language.setItemText(41, "Malagasy")
        self.Language.addItem("")
        self.Language.setItemText(42, "Malay")
        self.Language.addItem("")
        self.Language.setItemText(43, "Mongolian")
        self.Language.addItem("")
        self.Language.setItemText(44, "Norwegian")
        self.Language.addItem("")
        self.Language.setItemText(45, "NorwegianNynorsk")
        self.Language.addItem("")
        self.Language.setItemText(46, "Pashto")
        self.Language.addItem("")
        self.Language.setItemText(47, "Polish")
        self.Language.addItem("")
        self.Language.setItemText(48, "Portuguese")
        self.Language.addItem("")
        self.Language.setItemText(49, "PortugueseBR")
        self.Language.addItem("")
        self.Language.setItemText(50, "Romanian")
        self.Language.addItem("")
        self.Language.setItemText(51, "Russian")
        self.Language.addItem("")
        self.Language.setItemText(52, "Serbian")
        self.Language.addItem("")
        self.Language.setItemText(53, "SerbianLatin")
        self.Language.addItem("")
        self.Language.setItemText(54, "SimpChinese")
        self.Language.addItem("")
        self.Language.setItemText(55, "Slovak")
        self.Language.addItem("")
        self.Language.setItemText(56, "Slovenian")
        self.Language.addItem("")
        self.Language.setItemText(57, "Spanish")
        self.Language.addItem("")
        self.Language.setItemText(58, "SpanishInternational")
        self.Language.addItem("")
        self.Language.setItemText(59, "Swahili")
        self.Language.addItem("")
        self.Language.setItemText(60, "Swedish")
        self.Language.addItem("")
        self.Language.setItemText(61, "Thai")
        self.Language.addItem("")
        self.Language.setItemText(62, "TradChinese")
        self.Language.addItem("")
        self.Language.setItemText(63, "Turkish")
        self.Language.addItem("")
        self.Language.setItemText(64, "Ukranian")
        self.Language.addItem("")
        self.Language.setItemText(65, "Uzbek")
        self.Language.addItem("")
        self.Language.setItemText(66, "Valencian")
        self.Language.addItem("")
        self.Language.setItemText(67, "Vietnamese")
        self.Language.addItem("")
        self.Language.setItemText(68, "Welsh")
        self.Language.addItem("")
        self.Language.setItemText(69, "Yoruba")
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.Language)
        self.TrademarksLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.TrademarksLabel.setObjectName("TrademarksLabel")
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.LabelRole, self.TrademarksLabel)
        self.Trademarks = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Trademarks.setMaxLength(512)
        self.Trademarks.setObjectName("Trademarks")
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.FieldRole, self.Trademarks)
        self.verticalLayout_3.addWidget(self.DetailsGroupBox)
        self.VersionGroupBox = QtGui.QGroupBox(self.page_details)
        self.VersionGroupBox.setObjectName("VersionGroupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.VersionGroupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.DisplayVersionLabel = QtGui.QLabel(self.VersionGroupBox)
        self.DisplayVersionLabel.setObjectName("DisplayVersionLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.DisplayVersionLabel)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DisplayVersionBase = QtGui.QLineEdit(self.VersionGroupBox)
        self.DisplayVersionBase.setMaxLength(20)
        self.DisplayVersionBase.setObjectName("DisplayVersionBase")
        self.horizontalLayout_3.addWidget(self.DisplayVersionBase)
        self.DisplayVersionType = QtGui.QComboBox(self.VersionGroupBox)
        self.DisplayVersionType.setObjectName("DisplayVersionType")
        self.DisplayVersionType.addItem("")
        self.DisplayVersionType.setItemText(0, "Development Test")
        self.DisplayVersionType.addItem("")
        self.DisplayVersionType.setItemText(1, "Pre-Release")
        self.DisplayVersionType.addItem("")
        self.DisplayVersionType.setItemText(2, "(official release)")
        self.DisplayVersionType.addItem("")
        self.DisplayVersionType.setItemText(3, "Revision")
        self.horizontalLayout_3.addWidget(self.DisplayVersionType)
        self.DisplayVersionNum = QtGui.QSpinBox(self.VersionGroupBox)
        self.DisplayVersionNum.setMinimum(1)
        self.DisplayVersionNum.setObjectName("DisplayVersionNum")
        self.horizontalLayout_3.addWidget(self.DisplayVersionNum)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.PackageVersionLabel = QtGui.QLabel(self.VersionGroupBox)
        self.PackageVersionLabel.setObjectName("PackageVersionLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.PackageVersionLabel)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PackageVersion1 = QtGui.QSpinBox(self.VersionGroupBox)
        self.PackageVersion1.setMaximum(65535)
        self.PackageVersion1.setObjectName("PackageVersion1")
        self.horizontalLayout_5.addWidget(self.PackageVersion1)
        self.PackageVersionDot1 = QtGui.QLabel(self.VersionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PackageVersionDot1.sizePolicy().hasHeightForWidth())
        self.PackageVersionDot1.setSizePolicy(sizePolicy)
        self.PackageVersionDot1.setObjectName("PackageVersionDot1")
        self.horizontalLayout_5.addWidget(self.PackageVersionDot1)
        self.PackageVersion2 = QtGui.QSpinBox(self.VersionGroupBox)
        self.PackageVersion2.setMaximum(65535)
        self.PackageVersion2.setObjectName("PackageVersion2")
        self.horizontalLayout_5.addWidget(self.PackageVersion2)
        self.PackageVersionDot2 = QtGui.QLabel(self.VersionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PackageVersionDot2.sizePolicy().hasHeightForWidth())
        self.PackageVersionDot2.setSizePolicy(sizePolicy)
        self.PackageVersionDot2.setObjectName("PackageVersionDot2")
        self.horizontalLayout_5.addWidget(self.PackageVersionDot2)
        self.PackageVersion3 = QtGui.QSpinBox(self.VersionGroupBox)
        self.PackageVersion3.setMaximum(65535)
        self.PackageVersion3.setObjectName("PackageVersion3")
        self.horizontalLayout_5.addWidget(self.PackageVersion3)
        self.PackageVersionDot3 = QtGui.QLabel(self.VersionGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PackageVersionDot3.sizePolicy().hasHeightForWidth())
        self.PackageVersionDot3.setSizePolicy(sizePolicy)
        self.PackageVersionDot3.setObjectName("PackageVersionDot3")
        self.horizontalLayout_5.addWidget(self.PackageVersionDot3)
        self.PackageVersion4 = QtGui.QSpinBox(self.VersionGroupBox)
        self.PackageVersion4.setMaximum(65535)
        self.PackageVersion4.setObjectName("PackageVersion4")
        self.horizontalLayout_5.addWidget(self.PackageVersion4)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.VersionGroupBox)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.LicenseGroupBox = QtGui.QGroupBox(self.page_details)
        self.LicenseGroupBox.setObjectName("LicenseGroupBox")
        self.formLayout_5 = QtGui.QFormLayout(self.LicenseGroupBox)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName("formLayout_5")
        self.Shareable = QtGui.QCheckBox(self.LicenseGroupBox)
        self.Shareable.setObjectName("Shareable")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.Shareable)
        self.OpenSource = QtGui.QCheckBox(self.LicenseGroupBox)
        self.OpenSource.setObjectName("OpenSource")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.OpenSource)
        self.Freeware = QtGui.QCheckBox(self.LicenseGroupBox)
        self.Freeware.setObjectName("Freeware")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.Freeware)
        self.CommercialUse = QtGui.QCheckBox(self.LicenseGroupBox)
        self.CommercialUse.setObjectName("CommercialUse")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.CommercialUse)
        self.verticalLayout_5.addWidget(self.LicenseGroupBox)
        self.AdvancedGroupBox = QtGui.QGroupBox(self.page_details)
        self.AdvancedGroupBox.setObjectName("AdvancedGroupBox")
        self.formLayout_7 = QtGui.QFormLayout(self.AdvancedGroupBox)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setObjectName("formLayout_7")
        self.PluginsPathLabel = QtGui.QLabel(self.AdvancedGroupBox)
        self.PluginsPathLabel.setObjectName("PluginsPathLabel")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.PluginsPathLabel)
        self.PluginsPath = QtGui.QLineEdit(self.AdvancedGroupBox)
        self.PluginsPath.setMaxLength(256)
        self.PluginsPath.setObjectName("PluginsPath")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.PluginsPath)
        self.UsesDotNetVersionLabel = QtGui.QLabel(self.AdvancedGroupBox)
        self.UsesDotNetVersionLabel.setObjectName("UsesDotNetVersionLabel")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.UsesDotNetVersionLabel)
        self.UsesDotNetVersion = QtGui.QComboBox(self.AdvancedGroupBox)
        self.UsesDotNetVersion.setEditable(True)
        self.UsesDotNetVersion.setObjectName("UsesDotNetVersion")
        self.UsesDotNetVersion.addItem("")
        self.UsesDotNetVersion.setItemText(0, "None")
        self.UsesDotNetVersion.addItem("")
        self.UsesDotNetVersion.setItemText(1, "1.1")
        self.UsesDotNetVersion.addItem("")
        self.UsesDotNetVersion.setItemText(2, "2.0")
        self.UsesDotNetVersion.addItem("")
        self.UsesDotNetVersion.setItemText(3, "3.0")
        self.UsesDotNetVersion.addItem("")
        self.UsesDotNetVersion.setItemText(4, "3.5")
        self.UsesDotNetVersion.addItem("")
        self.UsesDotNetVersion.setItemText(5, "4.0")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.UsesDotNetVersion)
        self.UsesJava = QtGui.QCheckBox(self.AdvancedGroupBox)
        self.UsesJava.setObjectName("UsesJava")
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.UsesJava)
        self.EULAVersionLabel = QtGui.QLabel(self.AdvancedGroupBox)
        self.EULAVersionLabel.setObjectName("EULAVersionLabel")
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.LabelRole, self.EULAVersionLabel)
        self.EULAVersion = QtGui.QLineEdit(self.AdvancedGroupBox)
        self.EULAVersion.setMaxLength(128)
        self.EULAVersion.setObjectName("EULAVersion")
        self.formLayout_7.setWidget(4, QtGui.QFormLayout.FieldRole, self.EULAVersion)
        self.verticalLayout_5.addWidget(self.AdvancedGroupBox)
        spacerItem5 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 1, 0, 1, 2)
        self.pages.addWidget(self.page_details)
        self.page_launcher = QtGui.QWidget()
        self.page_launcher.setObjectName("page_launcher")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_launcher)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtGui.QLabel(self.page_launcher)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.pages.addWidget(self.page_launcher)
        self.page_compact = QtGui.QWidget()
        self.page_compact.setObjectName("page_compact")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_compact)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.compact_start = QtGui.QCommandLinkButton(self.page_compact)
        self.compact_start.setObjectName("compact_start")
        self.verticalLayout_7.addWidget(self.compact_start)
        self.compact_output = QtGui.QTextBrowser(self.page_compact)
        self.compact_output.setObjectName("compact_output")
        self.verticalLayout_7.addWidget(self.compact_output)
        self.groupBox_3 = QtGui.QGroupBox(self.page_compact)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.appcompactor_filesexcluded = QtGui.QLineEdit(self.groupBox_3)
        self.appcompactor_filesexcluded.setObjectName("appcompactor_filesexcluded")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.appcompactor_filesexcluded)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.appcompactor_additionalextensionsexcluded = QtGui.QLineEdit(self.groupBox_3)
        self.appcompactor_additionalextensionsexcluded.setObjectName("appcompactor_additionalextensionsexcluded")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.appcompactor_additionalextensionsexcluded)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.appcompactor_additionalextensionsincluded = QtGui.QLineEdit(self.groupBox_3)
        self.appcompactor_additionalextensionsincluded.setObjectName("appcompactor_additionalextensionsincluded")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.appcompactor_additionalextensionsincluded)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.pages.addWidget(self.page_compact)
        self.page_test = QtGui.QWidget()
        self.page_test.setObjectName("page_test")
        self.horizontalLayout = QtGui.QHBoxLayout(self.page_test)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.test_launcher_groupbox = QtGui.QGroupBox(self.page_test)
        self.test_launcher_groupbox.setObjectName("test_launcher_groupbox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.test_launcher_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.test_validates = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_validates.setEnabled(False)
        self.test_validates.setObjectName("test_validates")
        self.verticalLayout_2.addWidget(self.test_validates)
        self.test_runs = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_runs.setTristate(True)
        self.test_runs.setObjectName("test_runs")
        self.verticalLayout_2.addWidget(self.test_runs)
        self.test_run_platform = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_run_platform.setTristate(True)
        self.test_run_platform.setObjectName("test_run_platform")
        self.verticalLayout_2.addWidget(self.test_run_platform)
        self.test_run_direct = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_run_direct.setTristate(True)
        self.test_run_direct.setObjectName("test_run_direct")
        self.verticalLayout_2.addWidget(self.test_run_direct)
        self.test_workingdirectory = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_workingdirectory.setTristate(True)
        self.test_workingdirectory.setObjectName("test_workingdirectory")
        self.verticalLayout_2.addWidget(self.test_workingdirectory)
        self.test_path_spaces = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_path_spaces.setTristate(True)
        self.test_path_spaces.setObjectName("test_path_spaces")
        self.verticalLayout_2.addWidget(self.test_path_spaces)
        self.test_data = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_data.setTristate(True)
        self.test_data.setObjectName("test_data")
        self.verticalLayout_2.addWidget(self.test_data)
        self.test_fresh_installation = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_fresh_installation.setTristate(True)
        self.test_fresh_installation.setObjectName("test_fresh_installation")
        self.verticalLayout_2.addWidget(self.test_fresh_installation)
        self.test_upgrades = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_upgrades.setTristate(True)
        self.test_upgrades.setObjectName("test_upgrades")
        self.verticalLayout_2.addWidget(self.test_upgrades)
        self.test_drive_switches = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_drive_switches.setTristate(True)
        self.test_drive_switches.setObjectName("test_drive_switches")
        self.verticalLayout_2.addWidget(self.test_drive_switches)
        self.test_move_directory = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_move_directory.setTristate(True)
        self.test_move_directory.setObjectName("test_move_directory")
        self.verticalLayout_2.addWidget(self.test_move_directory)
        self.test_os = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_os.setTristate(True)
        self.test_os.setObjectName("test_os")
        self.verticalLayout_2.addWidget(self.test_os)
        self.test_multilingual = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_multilingual.setTristate(True)
        self.test_multilingual.setObjectName("test_multilingual")
        self.verticalLayout_2.addWidget(self.test_multilingual)
        spacerItem7 = QtGui.QSpacerItem(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout.addWidget(self.test_launcher_groupbox)
        self.test_help = QtGui.QTextBrowser(self.page_test)
        self.test_help.setSource(QtCore.QUrl("qrc:/checklist.html"))
        self.test_help.setOpenExternalLinks(True)
        self.test_help.setObjectName("test_help")
        self.horizontalLayout.addWidget(self.test_help)
        self.pages.addWidget(self.page_test)
        self.page_publish = QtGui.QWidget()
        self.page_publish.setObjectName("page_publish")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.page_publish)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self._4 = QtGui.QVBoxLayout()
        self._4.setObjectName("_4")
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._4.addItem(spacerItem9)
        self.build_installer = QtGui.QCommandLinkButton(self.page_publish)
        self.build_installer.setObjectName("build_installer")
        self._4.addWidget(self.build_installer)
        self.groupBox_4 = QtGui.QGroupBox(self.page_publish)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_6 = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName("label_3")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.installer_filename = QtGui.QLineEdit(self.groupBox_4)
        self.installer_filename.setMinimumSize(QtCore.QSize(300, 0))
        self.installer_filename.setReadOnly(True)
        self.installer_filename.setObjectName("installer_filename")
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.installer_filename)
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.installer_size = QtGui.QLineEdit(self.groupBox_4)
        self.installer_size.setReadOnly(True)
        self.installer_size.setObjectName("installer_size")
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.installer_size)
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.installer_size_installed = QtGui.QLineEdit(self.groupBox_4)
        self.installer_size_installed.setReadOnly(True)
        self.installer_size_installed.setObjectName("installer_size_installed")
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.installer_size_installed)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName("label_2")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.installer_md5 = QtGui.QLineEdit(self.groupBox_4)
        self.installer_md5.setReadOnly(True)
        self.installer_md5.setObjectName("installer_md5")
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.installer_md5)
        self._4.addWidget(self.groupBox_4)
        self.groupbox_upload = QtGui.QGroupBox(self.page_publish)
        self.groupbox_upload.setEnabled(False)
        self.groupbox_upload.setObjectName("groupbox_upload")
        self._3 = QtGui.QHBoxLayout(self.groupbox_upload)
        self._3.setObjectName("_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtGui.QPushButton(self.groupbox_upload)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 2, 1, 1)
        self.upload_to = QtGui.QComboBox(self.groupbox_upload)
        self.upload_to.setObjectName("upload_to")
        self.upload_to.addItem("")
        self.upload_to.addItem("")
        self.gridLayout_2.addWidget(self.upload_to, 1, 1, 1, 2)
        self.label_10 = QtGui.QLabel(self.groupbox_upload)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.groupbox_upload)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self._3.addLayout(self.gridLayout_2)
        self._4.addWidget(self.groupbox_upload)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self._4.addItem(spacerItem10)
        self.horizontalLayout_6.addLayout(self._4)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.pages.addWidget(self.page_publish)
        self.page_options = QtGui.QWidget()
        self.page_options.setObjectName("page_options")
        self.gridLayout_4 = QtGui.QGridLayout(self.page_options)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem12 = QtGui.QSpacerItem(86, 424, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 0, 0, 5, 1)
        spacerItem13 = QtGui.QSpacerItem(749, 60, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem13, 0, 1, 1, 3)
        spacerItem14 = QtGui.QSpacerItem(86, 424, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem14, 0, 4, 5, 1)
        self.options_installer_label = QtGui.QLabel(self.page_options)
        self.options_installer_label.setObjectName("options_installer_label")
        self.gridLayout_4.addWidget(self.options_installer_label, 1, 1, 1, 1)
        self.options_installer = QtGui.QLineEdit(self.page_options)
        self.options_installer.setMinimumSize(QtCore.QSize(400, 0))
        self.options_installer.setObjectName("options_installer")
        self.gridLayout_4.addWidget(self.options_installer, 1, 2, 1, 1)
        self.options_installer_browse = QtGui.QPushButton(self.page_options)
        self.options_installer_browse.setObjectName("options_installer_browse")
        self.gridLayout_4.addWidget(self.options_installer_browse, 1, 3, 1, 1)
        self.options_launcher_label = QtGui.QLabel(self.page_options)
        self.options_launcher_label.setObjectName("options_launcher_label")
        self.gridLayout_4.addWidget(self.options_launcher_label, 2, 1, 1, 1)
        self.options_launcher = QtGui.QLineEdit(self.page_options)
        self.options_launcher.setMinimumSize(QtCore.QSize(400, 0))
        self.options_launcher.setObjectName("options_launcher")
        self.gridLayout_4.addWidget(self.options_launcher, 2, 2, 1, 1)
        self.options_launcher_browse = QtGui.QPushButton(self.page_options)
        self.options_launcher_browse.setObjectName("options_launcher_browse")
        self.gridLayout_4.addWidget(self.options_launcher_browse, 2, 3, 1, 1)
        self.options_appcompactor_label = QtGui.QLabel(self.page_options)
        self.options_appcompactor_label.setObjectName("options_appcompactor_label")
        self.gridLayout_4.addWidget(self.options_appcompactor_label, 3, 1, 1, 1)
        self.options_appcompactor = QtGui.QLineEdit(self.page_options)
        self.options_appcompactor.setMinimumSize(QtCore.QSize(400, 0))
        self.options_appcompactor.setObjectName("options_appcompactor")
        self.gridLayout_4.addWidget(self.options_appcompactor, 3, 2, 1, 1)
        self.options_appcompactor_browse = QtGui.QPushButton(self.page_options)
        self.options_appcompactor_browse.setObjectName("options_appcompactor_browse")
        self.gridLayout_4.addWidget(self.options_appcompactor_browse, 3, 3, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(749, 256, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem15, 4, 1, 1, 3)
        self.pages.addWidget(self.page_options)
        self.page_about = QtGui.QWidget()
        self.page_about.setObjectName("page_about")
        self.gridLayout_3 = QtGui.QGridLayout(self.page_about)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem16 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 0, 0, 9, 1)
        self.about_productname = QtGui.QLabel(self.page_about)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.about_productname.setFont(font)
        self.about_productname.setObjectName("about_productname")
        self.gridLayout_3.addWidget(self.about_productname, 1, 1, 1, 1)
        self.about_version = QtGui.QLabel(self.page_about)
        self.about_version.setObjectName("about_version")
        self.gridLayout_3.addWidget(self.about_version, 2, 1, 1, 1)
        self.about_copyright = QtGui.QLabel(self.page_about)
        self.about_copyright.setObjectName("about_copyright")
        self.gridLayout_3.addWidget(self.about_copyright, 3, 1, 1, 1)
        self.about_description = QtGui.QLabel(self.page_about)
        self.about_description.setObjectName("about_description")
        self.gridLayout_3.addWidget(self.about_description, 5, 1, 1, 1)
        self.about_links = QtGui.QLabel(self.page_about)
        self.about_links.setOpenExternalLinks(True)
        self.about_links.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.about_links.setObjectName("about_links")
        self.gridLayout_3.addWidget(self.about_links, 7, 1, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 0, 2, 9, 1)
        spacerItem18 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem18, 0, 1, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem19, 8, 1, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem20, 4, 1, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem21, 6, 1, 1, 1)
        self.pages.addWidget(self.page_about)
        self.verticalLayout.addWidget(self.pages)
        MainWindow.setCentralWidget(self.centralwidget)
        self.start_open_label.setBuddy(self.start_open_package)
        self.start_create_label.setBuddy(self.start_create_package)
        self.NameLabel.setBuddy(self.Name)
        self.AppIDLabel.setBuddy(self.AppID)
        self.PublisherLabel.setBuddy(self.Publisher)
        self.HomepageLabel.setBuddy(self.Homepage)
        self.CategoryLabel.setBuddy(self.Category)
        self.DescriptionLabel.setBuddy(self.Description)
        self.LanguageLabel.setBuddy(self.Language)
        self.TrademarksLabel.setBuddy(self.Trademarks)
        self.DisplayVersionLabel.setBuddy(self.DisplayVersionBase)
        self.PackageVersionLabel.setBuddy(self.PackageVersion1)
        self.PluginsPathLabel.setBuddy(self.PluginsPath)
        self.UsesDotNetVersionLabel.setBuddy(self.UsesDotNetVersion)
        self.EULAVersionLabel.setBuddy(self.EULAVersion)
        self.label_7.setBuddy(self.appcompactor_filesexcluded)
        self.label_8.setBuddy(self.appcompactor_additionalextensionsexcluded)
        self.label_9.setBuddy(self.appcompactor_additionalextensionsincluded)
        self.options_installer_label.setBuddy(self.options_installer)
        self.options_launcher_label.setBuddy(self.options_launcher)
        self.options_appcompactor_label.setBuddy(self.options_appcompactor)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PortableApps.com Development Toolkit", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_start.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_arrow_1.setText(QtGui.QApplication.translate("MainWindow", "▶", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_details.setText(QtGui.QApplication.translate("MainWindow", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_arrow_2.setText(QtGui.QApplication.translate("MainWindow", "▶", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_launcher.setText(QtGui.QApplication.translate("MainWindow", "Launcher", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_arrow_3.setText(QtGui.QApplication.translate("MainWindow", "▶", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_compact.setText(QtGui.QApplication.translate("MainWindow", "Compact", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_arrow_4.setText(QtGui.QApplication.translate("MainWindow", "▶", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_test.setText(QtGui.QApplication.translate("MainWindow", "Test", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_arrow_5.setText(QtGui.QApplication.translate("MainWindow", "▶", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_publish.setText(QtGui.QApplication.translate("MainWindow", "Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_options.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.nav_about.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "I want to...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Open an existing package", None, QtGui.QApplication.UnicodeUTF8))
        self.start_open_label.setText(QtGui.QApplication.translate("MainWindow", "&Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.start_open_browse.setText(QtGui.QApplication.translate("MainWindow", "&Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Create a new portable app", None, QtGui.QApplication.UnicodeUTF8))
        self.start_create_label.setText(QtGui.QApplication.translate("MainWindow", "P&ath:", None, QtGui.QApplication.UnicodeUTF8))
        self.start_create_browse.setText(QtGui.QApplication.translate("MainWindow", "B&rowse...", None, QtGui.QApplication.UnicodeUTF8))
        self.DetailsGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "App details", None, QtGui.QApplication.UnicodeUTF8))
        self.NameLabel.setText(QtGui.QApplication.translate("MainWindow", "Portable app &name", None, QtGui.QApplication.UnicodeUTF8))
        self.AppIDLabel.setText(QtGui.QApplication.translate("MainWindow", "&App ID", None, QtGui.QApplication.UnicodeUTF8))
        self.PublisherLabel.setText(QtGui.QApplication.translate("MainWindow", "&Publisher", None, QtGui.QApplication.UnicodeUTF8))
        self.HomepageLabel.setText(QtGui.QApplication.translate("MainWindow", "&Homepage", None, QtGui.QApplication.UnicodeUTF8))
        self.CategoryLabel.setText(QtGui.QApplication.translate("MainWindow", "Cate&gory", None, QtGui.QApplication.UnicodeUTF8))
        self.DescriptionLabel.setText(QtGui.QApplication.translate("MainWindow", "&Description", None, QtGui.QApplication.UnicodeUTF8))
        self.LanguageLabel.setText(QtGui.QApplication.translate("MainWindow", "&Language", None, QtGui.QApplication.UnicodeUTF8))
        self.TrademarksLabel.setText(QtGui.QApplication.translate("MainWindow", "&Trademarks", None, QtGui.QApplication.UnicodeUTF8))
        self.VersionGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.DisplayVersionLabel.setText(QtGui.QApplication.translate("MainWindow", "Display &version", None, QtGui.QApplication.UnicodeUTF8))
        self.PackageVersionLabel.setText(QtGui.QApplication.translate("MainWindow", "Pac&kage version", None, QtGui.QApplication.UnicodeUTF8))
        self.PackageVersionDot1.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.PackageVersionDot2.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.PackageVersionDot3.setText(QtGui.QApplication.translate("MainWindow", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.LicenseGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.Shareable.setText(QtGui.QApplication.translate("MainWindow", "Sharea&ble", None, QtGui.QApplication.UnicodeUTF8))
        self.OpenSource.setText(QtGui.QApplication.translate("MainWindow", "Op&en source", None, QtGui.QApplication.UnicodeUTF8))
        self.Freeware.setText(QtGui.QApplication.translate("MainWindow", "&Freeware", None, QtGui.QApplication.UnicodeUTF8))
        self.CommercialUse.setText(QtGui.QApplication.translate("MainWindow", "Co&mmercial use", None, QtGui.QApplication.UnicodeUTF8))
        self.AdvancedGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.PluginsPathLabel.setText(QtGui.QApplication.translate("MainWindow", "P&lugins path", None, QtGui.QApplication.UnicodeUTF8))
        self.UsesDotNetVersionLabel.setText(QtGui.QApplication.translate("MainWindow", "&Requires .NET version", None, QtGui.QApplication.UnicodeUTF8))
        self.UsesJava.setText(QtGui.QApplication.translate("MainWindow", "Uses &Java", None, QtGui.QApplication.UnicodeUTF8))
        self.EULAVersionLabel.setText(QtGui.QApplication.translate("MainWindow", "E&ULA version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<p>A really advanced sort of editor and manager for PortableApps.com Launcher configuration will go here.</p><p>Unfortunately, it\'s going to be <em>so</em> powerful that it\'s not ready yet.</p>", None, QtGui.QApplication.UnicodeUTF8))
        self.compact_start.setText(QtGui.QApplication.translate("MainWindow", "Start compacting app", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Advanced configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "&Files to exclude:", None, QtGui.QApplication.UnicodeUTF8))
        self.appcompactor_filesexcluded.setToolTip(QtGui.QApplication.translate("MainWindow", "<p>Enter a pipe-separated list of filenames to exclude from compression.  Wildcards are not accepted.</p><p><strong>Example:</strong> <code>msvcm90.dll|msvcp90.dll|mscvr90.dll</code></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Additional extensions &excluded:", None, QtGui.QApplication.UnicodeUTF8))
        self.appcompactor_additionalextensionsexcluded.setToolTip(QtGui.QApplication.translate("MainWindow", "<p>Enter a pipe-separated list of file extensions to exclude from compression.  Wildcards are not accepted.</p><p><strong>Example:</strong> <code>pyd|irc</code></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Additional extensions &included:", None, QtGui.QApplication.UnicodeUTF8))
        self.appcompactor_additionalextensionsincluded.setToolTip(QtGui.QApplication.translate("MainWindow", "<p>Enter a pipe-separated list of additional file extensions to compress.  Wildcards are not accepted.</p><p><strong>Example:</strong> <code>example|beta</code></p>", None, QtGui.QApplication.UnicodeUTF8))
        self.test_launcher_groupbox.setTitle(QtGui.QApplication.translate("MainWindow", "Launcher", None, QtGui.QApplication.UnicodeUTF8))
        self.test_validates.setText(QtGui.QApplication.translate("MainWindow", "Does it validate with no errors or warnings?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_runs.setText(QtGui.QApplication.translate("MainWindow", "Does it run?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_run_platform.setText(QtGui.QApplication.translate("MainWindow", "Does it run from the PortableApps.com Platform?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_run_direct.setText(QtGui.QApplication.translate("MainWindow", "Does it run by running the launcher executable directly?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_workingdirectory.setText(QtGui.QApplication.translate("MainWindow", "Is it working directory independent?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_path_spaces.setText(QtGui.QApplication.translate("MainWindow", "Does it run from a path with spaces in it?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_data.setText(QtGui.QApplication.translate("MainWindow", "Is data stored in the Data directory?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_fresh_installation.setText(QtGui.QApplication.translate("MainWindow", "Does a fresh installation work?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_upgrades.setText(QtGui.QApplication.translate("MainWindow", "Do upgrades from a previous version work completely?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_drive_switches.setText(QtGui.QApplication.translate("MainWindow", "Does it run from a different drive letter?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_move_directory.setText(QtGui.QApplication.translate("MainWindow", "Does it run if you move the directory?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_os.setText(QtGui.QApplication.translate("MainWindow", "Does it run on different operating systems?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_multilingual.setText(QtGui.QApplication.translate("MainWindow", "If multilingual, is automatic language switching implemented?", None, QtGui.QApplication.UnicodeUTF8))
        self.build_installer.setText(QtGui.QApplication.translate("MainWindow", "Build installer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "File size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Installed size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "MD5 checksum:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupbox_upload.setTitle(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Configure targets", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_to.setItemText(0, QtGui.QApplication.translate("MainWindow", "SourceForge (portableapps)", None, QtGui.QApplication.UnicodeUTF8))
        self.upload_to.setItemText(1, QtGui.QApplication.translate("MainWindow", "portableapps.chrismorgan.info", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Upload to:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Upload it", None, QtGui.QApplication.UnicodeUTF8))
        self.options_installer_label.setText(QtGui.QApplication.translate("MainWindow", "PortableApps.com &Installer path:", None, QtGui.QApplication.UnicodeUTF8))
        self.options_installer_browse.setText(QtGui.QApplication.translate("MainWindow", "&Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.options_launcher_label.setText(QtGui.QApplication.translate("MainWindow", "PortableApps.com &Launcher path:", None, QtGui.QApplication.UnicodeUTF8))
        self.options_launcher_browse.setText(QtGui.QApplication.translate("MainWindow", "B&rowse...", None, QtGui.QApplication.UnicodeUTF8))
        self.options_appcompactor_label.setText(QtGui.QApplication.translate("MainWindow", "PortableApps.com &AppCompactor path:", None, QtGui.QApplication.UnicodeUTF8))
        self.options_appcompactor_browse.setText(QtGui.QApplication.translate("MainWindow", "Br&owse...", None, QtGui.QApplication.UnicodeUTF8))
        self.about_productname.setText(QtGui.QApplication.translate("MainWindow", "PortableApps.com Development Toolkit", None, QtGui.QApplication.UnicodeUTF8))
        self.about_version.setText(QtGui.QApplication.translate("MainWindow", "Version 1.0 Alpha 2", None, QtGui.QApplication.UnicodeUTF8))
        self.about_copyright.setText(QtGui.QApplication.translate("MainWindow", "© 2011 PortableApps.com (Chris Morgan)", None, QtGui.QApplication.UnicodeUTF8))
        self.about_description.setText(QtGui.QApplication.translate("MainWindow", "A utility to assist in the creation of high quality portable apps.", None, QtGui.QApplication.UnicodeUTF8))
        self.about_links.setText(QtGui.QApplication.translate("MainWindow", "<p>If you find bugs or have suggestions to make, please contact us.</p>\n"
"<p><strong>Links:</strong><br><a href=\"http://portableapps.com\">PortableApps.com</a><br>\n"
"<a href=\"http://portableapps.com/development\">PortableApps.com/Development</a></p>", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
