# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend/guiqt/ui/pagetest.ui'
#
#      by: pyside-uic 0.2.9 running on PySide 1.0.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PageTest(object):
    def setupUi(self, pagetest):
        pagetest.setObjectName("pagetest")
        pagetest.setGeometry(QtCore.QRect(0, 0, 960, 445))
        self.horizontalLayout = QtGui.QHBoxLayout(pagetest)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.test_launcher_groupbox = QtGui.QGroupBox(pagetest)
        self.test_launcher_groupbox.setObjectName("test_launcher_groupbox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.test_launcher_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.test_validates = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_validates.setEnabled(False)
        self.test_validates.setObjectName("test_validates")
        self.verticalLayout_2.addWidget(self.test_validates)
        self.test_runs = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_runs.setTristate(True)
        self.test_runs.setObjectName("test_runs")
        self.verticalLayout_2.addWidget(self.test_runs)
        self.test_run_platform = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_run_platform.setTristate(True)
        self.test_run_platform.setObjectName("test_run_platform")
        self.verticalLayout_2.addWidget(self.test_run_platform)
        self.test_run_direct = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_run_direct.setTristate(True)
        self.test_run_direct.setObjectName("test_run_direct")
        self.verticalLayout_2.addWidget(self.test_run_direct)
        self.test_workingdirectory = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_workingdirectory.setTristate(True)
        self.test_workingdirectory.setObjectName("test_workingdirectory")
        self.verticalLayout_2.addWidget(self.test_workingdirectory)
        self.test_path_spaces = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_path_spaces.setTristate(True)
        self.test_path_spaces.setObjectName("test_path_spaces")
        self.verticalLayout_2.addWidget(self.test_path_spaces)
        self.test_data = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_data.setTristate(True)
        self.test_data.setObjectName("test_data")
        self.verticalLayout_2.addWidget(self.test_data)
        self.test_fresh_installation = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_fresh_installation.setTristate(True)
        self.test_fresh_installation.setObjectName("test_fresh_installation")
        self.verticalLayout_2.addWidget(self.test_fresh_installation)
        self.test_upgrades = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_upgrades.setTristate(True)
        self.test_upgrades.setObjectName("test_upgrades")
        self.verticalLayout_2.addWidget(self.test_upgrades)
        self.test_drive_switches = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_drive_switches.setTristate(True)
        self.test_drive_switches.setObjectName("test_drive_switches")
        self.verticalLayout_2.addWidget(self.test_drive_switches)
        self.test_move_directory = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_move_directory.setTristate(True)
        self.test_move_directory.setObjectName("test_move_directory")
        self.verticalLayout_2.addWidget(self.test_move_directory)
        self.test_os = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_os.setTristate(True)
        self.test_os.setObjectName("test_os")
        self.verticalLayout_2.addWidget(self.test_os)
        self.test_multilingual = QtGui.QCheckBox(self.test_launcher_groupbox)
        self.test_multilingual.setTristate(True)
        self.test_multilingual.setObjectName("test_multilingual")
        self.verticalLayout_2.addWidget(self.test_multilingual)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.test_launcher_groupbox)
        self.test_help = QtGui.QTextBrowser(pagetest)
        self.test_help.setSource(QtCore.QUrl("qrc:/checklist.html"))
        self.test_help.setOpenExternalLinks(True)
        self.test_help.setObjectName("test_help")
        self.horizontalLayout.addWidget(self.test_help)

        self.retranslateUi(pagetest)
        QtCore.QMetaObject.connectSlotsByName(pagetest)

    def retranslateUi(self, pagetest):
        self.test_launcher_groupbox.setTitle(QtGui.QApplication.translate("PageTest", "Launcher", None, QtGui.QApplication.UnicodeUTF8))
        self.test_validates.setText(QtGui.QApplication.translate("PageTest", "Does it validate with no errors or warnings?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_runs.setText(QtGui.QApplication.translate("PageTest", "Does it run?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_run_platform.setText(QtGui.QApplication.translate("PageTest", "Does it run from the PortableApps.com Platform?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_run_direct.setText(QtGui.QApplication.translate("PageTest", "Does it run by running the launcher executable directly?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_workingdirectory.setText(QtGui.QApplication.translate("PageTest", "Is it working directory independent?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_path_spaces.setText(QtGui.QApplication.translate("PageTest", "Does it run from a path with spaces in it?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_data.setText(QtGui.QApplication.translate("PageTest", "Is data stored in the Data directory?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_fresh_installation.setText(QtGui.QApplication.translate("PageTest", "Does a fresh installation work?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_upgrades.setText(QtGui.QApplication.translate("PageTest", "Do upgrades from a previous version work completely?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_drive_switches.setText(QtGui.QApplication.translate("PageTest", "Does it run from a different drive letter?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_move_directory.setText(QtGui.QApplication.translate("PageTest", "Does it run if you move the directory?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_os.setText(QtGui.QApplication.translate("PageTest", "Does it run on different operating systems?", None, QtGui.QApplication.UnicodeUTF8))
        self.test_multilingual.setText(QtGui.QApplication.translate("PageTest", "If multilingual, is automatic language switching implemented?", None, QtGui.QApplication.UnicodeUTF8))

