# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/pagetest.ui'
#
#      by: pyside-uic 0.2.9 running on PySide 1.0.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_PageTest(object):
    def setupUi(self, PageTest):
        PageTest.setObjectName("PageTest")
        PageTest.resize(960, 445)
        self.horizontalLayout = QtGui.QHBoxLayout(PageTest)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabwidget = QtGui.QTabWidget(PageTest)
        self.tabwidget.setObjectName("tabwidget")
        self.validate_tab = QtGui.QWidget()
        self.validate_tab.setObjectName("validate_tab")
        self.gridLayout = QtGui.QGridLayout(self.validate_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.validation_results_html = QtGui.QTextBrowser(self.validate_tab)
        self.validation_results_html.setObjectName("validation_results_html")
        self.gridLayout.addWidget(self.validation_results_html, 0, 0, 2, 1)
        self.validation_results_plain = QtGui.QPlainTextEdit(self.validate_tab)
        self.validation_results_plain.setObjectName("validation_results_plain")
        self.gridLayout.addWidget(self.validation_results_plain, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.validate_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 2)
        self.tabwidget.addTab(self.validate_tab, "")
        self.checklist_tab = QtGui.QWidget()
        self.checklist_tab.setObjectName("checklist_tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.checklist_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.launcher_groupbox = QtGui.QGroupBox(self.checklist_tab)
        self.launcher_groupbox.setObjectName("launcher_groupbox")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.launcher_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checklist_runs = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_runs.setTristate(True)
        self.checklist_runs.setObjectName("checklist_runs")
        self.verticalLayout_2.addWidget(self.checklist_runs)
        self.checklist_run_platform = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_run_platform.setTristate(True)
        self.checklist_run_platform.setObjectName("checklist_run_platform")
        self.verticalLayout_2.addWidget(self.checklist_run_platform)
        self.checklist_run_direct = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_run_direct.setTristate(True)
        self.checklist_run_direct.setObjectName("checklist_run_direct")
        self.verticalLayout_2.addWidget(self.checklist_run_direct)
        self.checklist_workingdirectory = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_workingdirectory.setTristate(True)
        self.checklist_workingdirectory.setObjectName("checklist_workingdirectory")
        self.verticalLayout_2.addWidget(self.checklist_workingdirectory)
        self.checklist_path_spaces = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_path_spaces.setTristate(True)
        self.checklist_path_spaces.setObjectName("checklist_path_spaces")
        self.verticalLayout_2.addWidget(self.checklist_path_spaces)
        self.checklist_data = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_data.setTristate(True)
        self.checklist_data.setObjectName("checklist_data")
        self.verticalLayout_2.addWidget(self.checklist_data)
        self.checklist_fresh_installation = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_fresh_installation.setTristate(True)
        self.checklist_fresh_installation.setObjectName("checklist_fresh_installation")
        self.verticalLayout_2.addWidget(self.checklist_fresh_installation)
        self.checklist_upgrades = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_upgrades.setTristate(True)
        self.checklist_upgrades.setObjectName("checklist_upgrades")
        self.verticalLayout_2.addWidget(self.checklist_upgrades)
        self.checklist_drive_switches = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_drive_switches.setTristate(True)
        self.checklist_drive_switches.setObjectName("checklist_drive_switches")
        self.verticalLayout_2.addWidget(self.checklist_drive_switches)
        self.checklist_move_directory = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_move_directory.setTristate(True)
        self.checklist_move_directory.setObjectName("checklist_move_directory")
        self.verticalLayout_2.addWidget(self.checklist_move_directory)
        self.checklist_os = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_os.setTristate(True)
        self.checklist_os.setObjectName("checklist_os")
        self.verticalLayout_2.addWidget(self.checklist_os)
        self.checklist_multilingual = QtGui.QCheckBox(self.launcher_groupbox)
        self.checklist_multilingual.setTristate(True)
        self.checklist_multilingual.setObjectName("checklist_multilingual")
        self.verticalLayout_2.addWidget(self.checklist_multilingual)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.launcher_groupbox)
        self.checklist_help = QtGui.QTextBrowser(self.checklist_tab)
        self.checklist_help.setSource(QtCore.QUrl("qrc:/checklist.html"))
        self.checklist_help.setOpenExternalLinks(True)
        self.checklist_help.setObjectName("checklist_help")
        self.horizontalLayout_2.addWidget(self.checklist_help)
        self.tabwidget.addTab(self.checklist_tab, "")
        self.horizontalLayout.addWidget(self.tabwidget)

        self.retranslateUi(PageTest)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PageTest)

    def retranslateUi(self, PageTest):
        self.label_2.setText(QtGui.QApplication.translate("PageTest", "HTML output (for putting in PortableApps.com forums)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.validate_tab), QtGui.QApplication.translate("PageTest", "Validation", None, QtGui.QApplication.UnicodeUTF8))
        self.launcher_groupbox.setTitle(QtGui.QApplication.translate("PageTest", "Launcher", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_runs.setText(QtGui.QApplication.translate("PageTest", "Does it run?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_run_platform.setText(QtGui.QApplication.translate("PageTest", "Does it run from the PortableApps.com Platform?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_run_direct.setText(QtGui.QApplication.translate("PageTest", "Does it run by running the launcher executable directly?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_workingdirectory.setText(QtGui.QApplication.translate("PageTest", "Is it working directory independent?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_path_spaces.setText(QtGui.QApplication.translate("PageTest", "Does it run from a path with spaces in it?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_data.setText(QtGui.QApplication.translate("PageTest", "Is data stored in the Data directory?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_fresh_installation.setText(QtGui.QApplication.translate("PageTest", "Does a fresh installation work?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_upgrades.setText(QtGui.QApplication.translate("PageTest", "Do upgrades from a previous version work completely?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_drive_switches.setText(QtGui.QApplication.translate("PageTest", "Does it run from a different drive letter?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_move_directory.setText(QtGui.QApplication.translate("PageTest", "Does it run if you move the directory?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_os.setText(QtGui.QApplication.translate("PageTest", "Does it run on different operating systems?", None, QtGui.QApplication.UnicodeUTF8))
        self.checklist_multilingual.setText(QtGui.QApplication.translate("PageTest", "If multilingual, is automatic language switching implemented?", None, QtGui.QApplication.UnicodeUTF8))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.checklist_tab), QtGui.QApplication.translate("PageTest", "Release checklist", None, QtGui.QApplication.UnicodeUTF8))

