# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/appinfo.ui'
#
# Created: Thu Oct 28 13:09:48 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AppInfoDialog(object):
    def setupUi(self, AppInfoDialog):
        AppInfoDialog.setObjectName("AppInfoDialog")
        AppInfoDialog.resize(883, 457)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AppInfoDialog.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(AppInfoDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        self.DetailsGroupBox = QtGui.QGroupBox(AppInfoDialog)
        self.DetailsGroupBox.setObjectName("DetailsGroupBox")
        self.formLayout_4 = QtGui.QFormLayout(self.DetailsGroupBox)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.NameLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.NameLabel.setObjectName("NameLabel")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.NameLabel)
        self.Name = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Name.setMaxLength(128)
        self.Name.setObjectName("Name")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.Name)
        self.AppIDLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.AppIDLabel.setObjectName("AppIDLabel")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.AppIDLabel)
        self.AppID = QtGui.QLineEdit(self.DetailsGroupBox)
        self.AppID.setMaxLength(128)
        self.AppID.setObjectName("AppID")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.AppID)
        self.PublisherLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.PublisherLabel.setObjectName("PublisherLabel")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.PublisherLabel)
        self.Publisher = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Publisher.setMaxLength(128)
        self.Publisher.setObjectName("Publisher")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.Publisher)
        self.HomepageLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.HomepageLabel.setObjectName("HomepageLabel")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.HomepageLabel)
        self.Homepage = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Homepage.setMaxLength(128)
        self.Homepage.setObjectName("Homepage")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.Homepage)
        self.CategoryLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.CategoryLabel.setObjectName("CategoryLabel")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.CategoryLabel)
        self.Category = QtGui.QComboBox(self.DetailsGroupBox)
        self.Category.setObjectName("Category")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.Category.addItem("")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.Category)
        self.DescriptionLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.DescriptionLabel.setObjectName("DescriptionLabel")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.DescriptionLabel)
        self.Description = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Description.setMaxLength(512)
        self.Description.setObjectName("Description")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.Description)
        self.LanguageLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.LanguageLabel.setObjectName("LanguageLabel")
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.LabelRole, self.LanguageLabel)
        self.Language = QtGui.QComboBox(self.DetailsGroupBox)
        self.Language.setObjectName("Language")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.Language.addItem("")
        self.formLayout_4.setWidget(6, QtGui.QFormLayout.FieldRole, self.Language)
        self.TrademarksLabel = QtGui.QLabel(self.DetailsGroupBox)
        self.TrademarksLabel.setObjectName("TrademarksLabel")
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.LabelRole, self.TrademarksLabel)
        self.Trademarks = QtGui.QLineEdit(self.DetailsGroupBox)
        self.Trademarks.setMaxLength(512)
        self.Trademarks.setObjectName("Trademarks")
        self.formLayout_4.setWidget(7, QtGui.QFormLayout.FieldRole, self.Trademarks)
        self.gridlayout.addWidget(self.DetailsGroupBox, 0, 0, 3, 1)
        self.VersionGroupBox = QtGui.QGroupBox(AppInfoDialog)
        self.VersionGroupBox.setObjectName("VersionGroupBox")
        self.formLayout = QtGui.QFormLayout(self.VersionGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.DisplayVersionLabel = QtGui.QLabel(self.VersionGroupBox)
        self.DisplayVersionLabel.setObjectName("DisplayVersionLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.DisplayVersionLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DisplayVersionBase = QtGui.QLineEdit(self.VersionGroupBox)
        self.DisplayVersionBase.setMaxLength(20)
        self.DisplayVersionBase.setObjectName("DisplayVersionBase")
        self.horizontalLayout.addWidget(self.DisplayVersionBase)
        self.DisplayVersionType = QtGui.QComboBox(self.VersionGroupBox)
        self.DisplayVersionType.setObjectName("DisplayVersionType")
        self.DisplayVersionType.addItem("")
        self.DisplayVersionType.addItem("")
        self.DisplayVersionType.addItem("")
        self.DisplayVersionType.addItem("")
        self.horizontalLayout.addWidget(self.DisplayVersionType)
        self.spinBox = QtGui.QSpinBox(self.VersionGroupBox)
        self.spinBox.setMinimum(1)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.PackageVersionLabel = QtGui.QLabel(self.VersionGroupBox)
        self.PackageVersionLabel.setObjectName("PackageVersionLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.PackageVersionLabel)
        self.PackageVersion = QtGui.QLineEdit(self.VersionGroupBox)
        self.PackageVersion.setObjectName("PackageVersion")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.PackageVersion)
        self.gridlayout.addWidget(self.VersionGroupBox, 0, 1, 1, 1)
        self.LicenseGroupBox = QtGui.QGroupBox(AppInfoDialog)
        self.LicenseGroupBox.setObjectName("LicenseGroupBox")
        self.formLayout_5 = QtGui.QFormLayout(self.LicenseGroupBox)
        self.formLayout_5.setObjectName("formLayout_5")
        self.Shareable = QtGui.QCheckBox(self.LicenseGroupBox)
        self.Shareable.setObjectName("Shareable")
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.Shareable)
        self.OpenSource = QtGui.QCheckBox(self.LicenseGroupBox)
        self.OpenSource.setObjectName("OpenSource")
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.OpenSource)
        self.Freeware = QtGui.QCheckBox(self.LicenseGroupBox)
        self.Freeware.setObjectName("Freeware")
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.Freeware)
        self.CommercialUse = QtGui.QCheckBox(self.LicenseGroupBox)
        self.CommercialUse.setObjectName("CommercialUse")
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.CommercialUse)
        self.gridlayout.addWidget(self.LicenseGroupBox, 1, 1, 1, 1)
        self.AdvancedGroupBox = QtGui.QGroupBox(AppInfoDialog)
        self.AdvancedGroupBox.setObjectName("AdvancedGroupBox")
        self.formLayout_7 = QtGui.QFormLayout(self.AdvancedGroupBox)
        self.formLayout_7.setObjectName("formLayout_7")
        self.PluginsPathLabel = QtGui.QLabel(self.AdvancedGroupBox)
        self.PluginsPathLabel.setObjectName("PluginsPathLabel")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.PluginsPathLabel)
        self.PluginsPath = QtGui.QLineEdit(self.AdvancedGroupBox)
        self.PluginsPath.setMaxLength(256)
        self.PluginsPath.setObjectName("PluginsPath")
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.PluginsPath)
        self.label = QtGui.QLabel(self.AdvancedGroupBox)
        self.label.setObjectName("label")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.comboBox = QtGui.QComboBox(self.AdvancedGroupBox)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBox)
        self.UsesJava = QtGui.QCheckBox(self.AdvancedGroupBox)
        self.UsesJava.setObjectName("UsesJava")
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.UsesJava)
        self.gridlayout.addWidget(self.AdvancedGroupBox, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridlayout)
        self.buttonBox = QtGui.QDialogButtonBox(AppInfoDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AppInfoDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), AppInfoDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), AppInfoDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AppInfoDialog)

    def retranslateUi(self, AppInfoDialog):
        AppInfoDialog.setWindowTitle(QtGui.QApplication.translate("AppInfoDialog", "App details", None, QtGui.QApplication.UnicodeUTF8))
        self.DetailsGroupBox.setTitle(QtGui.QApplication.translate("AppInfoDialog", "App details", None, QtGui.QApplication.UnicodeUTF8))
        self.NameLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Portable app name", None, QtGui.QApplication.UnicodeUTF8))
        self.AppIDLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "App ID", None, QtGui.QApplication.UnicodeUTF8))
        self.PublisherLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Publisher", None, QtGui.QApplication.UnicodeUTF8))
        self.HomepageLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Homepage", None, QtGui.QApplication.UnicodeUTF8))
        self.CategoryLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Category", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(0, QtGui.QApplication.translate("AppInfoDialog", "Accessibility", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(1, QtGui.QApplication.translate("AppInfoDialog", "Development", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(2, QtGui.QApplication.translate("AppInfoDialog", "Education", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(3, QtGui.QApplication.translate("AppInfoDialog", "Games", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(4, QtGui.QApplication.translate("AppInfoDialog", "Graphics & Pictures", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(5, QtGui.QApplication.translate("AppInfoDialog", "Internet", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(6, QtGui.QApplication.translate("AppInfoDialog", "Music & Video", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(7, QtGui.QApplication.translate("AppInfoDialog", "Office", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(8, QtGui.QApplication.translate("AppInfoDialog", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.Category.setItemText(9, QtGui.QApplication.translate("AppInfoDialog", "Utilities", None, QtGui.QApplication.UnicodeUTF8))
        self.DescriptionLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.LanguageLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(0, QtGui.QApplication.translate("AppInfoDialog", "Multilingual", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(1, QtGui.QApplication.translate("AppInfoDialog", "English", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(2, QtGui.QApplication.translate("AppInfoDialog", "Afrikaans", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(3, QtGui.QApplication.translate("AppInfoDialog", "Albanian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(4, QtGui.QApplication.translate("AppInfoDialog", "Arabic", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(5, QtGui.QApplication.translate("AppInfoDialog", "Armenian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(6, QtGui.QApplication.translate("AppInfoDialog", "Basque", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(7, QtGui.QApplication.translate("AppInfoDialog", "Belarusian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(8, QtGui.QApplication.translate("AppInfoDialog", "Bosnian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(9, QtGui.QApplication.translate("AppInfoDialog", "Breton", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(10, QtGui.QApplication.translate("AppInfoDialog", "Bulgarian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(11, QtGui.QApplication.translate("AppInfoDialog", "Catalan", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(12, QtGui.QApplication.translate("AppInfoDialog", "Cibemba", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(13, QtGui.QApplication.translate("AppInfoDialog", "Croatian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(14, QtGui.QApplication.translate("AppInfoDialog", "Czech", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(15, QtGui.QApplication.translate("AppInfoDialog", "Danish", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(16, QtGui.QApplication.translate("AppInfoDialog", "Dutch", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(17, QtGui.QApplication.translate("AppInfoDialog", "Efik", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(18, QtGui.QApplication.translate("AppInfoDialog", "Estonian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(19, QtGui.QApplication.translate("AppInfoDialog", "Farsi", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(20, QtGui.QApplication.translate("AppInfoDialog", "Finnish", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(21, QtGui.QApplication.translate("AppInfoDialog", "French", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(22, QtGui.QApplication.translate("AppInfoDialog", "Galician", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(23, QtGui.QApplication.translate("AppInfoDialog", "Georgian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(24, QtGui.QApplication.translate("AppInfoDialog", "German", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(25, QtGui.QApplication.translate("AppInfoDialog", "Greek", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(26, QtGui.QApplication.translate("AppInfoDialog", "Hebrew", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(27, QtGui.QApplication.translate("AppInfoDialog", "Hungarian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(28, QtGui.QApplication.translate("AppInfoDialog", "Icelandic", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(29, QtGui.QApplication.translate("AppInfoDialog", "Igbo", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(30, QtGui.QApplication.translate("AppInfoDialog", "Indonesian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(31, QtGui.QApplication.translate("AppInfoDialog", "Irish", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(32, QtGui.QApplication.translate("AppInfoDialog", "Italian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(33, QtGui.QApplication.translate("AppInfoDialog", "Japanese", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(34, QtGui.QApplication.translate("AppInfoDialog", "Khmer", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(35, QtGui.QApplication.translate("AppInfoDialog", "Korean", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(36, QtGui.QApplication.translate("AppInfoDialog", "Kurdish", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(37, QtGui.QApplication.translate("AppInfoDialog", "Latvian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(38, QtGui.QApplication.translate("AppInfoDialog", "Lithuanian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(39, QtGui.QApplication.translate("AppInfoDialog", "Luxembourgish", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(40, QtGui.QApplication.translate("AppInfoDialog", "Macedonian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(41, QtGui.QApplication.translate("AppInfoDialog", "Malagasy", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(42, QtGui.QApplication.translate("AppInfoDialog", "Malay", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(43, QtGui.QApplication.translate("AppInfoDialog", "Mongolian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(44, QtGui.QApplication.translate("AppInfoDialog", "Norwegian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(45, QtGui.QApplication.translate("AppInfoDialog", "NorwegianNynorsk", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(46, QtGui.QApplication.translate("AppInfoDialog", "Pashto", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(47, QtGui.QApplication.translate("AppInfoDialog", "Polish", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(48, QtGui.QApplication.translate("AppInfoDialog", "Portuguese", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(49, QtGui.QApplication.translate("AppInfoDialog", "PortugueseBR", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(50, QtGui.QApplication.translate("AppInfoDialog", "Romanian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(51, QtGui.QApplication.translate("AppInfoDialog", "Russian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(52, QtGui.QApplication.translate("AppInfoDialog", "Serbian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(53, QtGui.QApplication.translate("AppInfoDialog", "SerbianLatin", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(54, QtGui.QApplication.translate("AppInfoDialog", "SimpChinese", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(55, QtGui.QApplication.translate("AppInfoDialog", "Slovak", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(56, QtGui.QApplication.translate("AppInfoDialog", "Slovenian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(57, QtGui.QApplication.translate("AppInfoDialog", "Spanish", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(58, QtGui.QApplication.translate("AppInfoDialog", "SpanishInternational", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(59, QtGui.QApplication.translate("AppInfoDialog", "Swahili", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(60, QtGui.QApplication.translate("AppInfoDialog", "Swedish", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(61, QtGui.QApplication.translate("AppInfoDialog", "Thai", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(62, QtGui.QApplication.translate("AppInfoDialog", "TradChinese", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(63, QtGui.QApplication.translate("AppInfoDialog", "Turkish", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(64, QtGui.QApplication.translate("AppInfoDialog", "Ukranian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(65, QtGui.QApplication.translate("AppInfoDialog", "Uzbek", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(66, QtGui.QApplication.translate("AppInfoDialog", "Valencian", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(67, QtGui.QApplication.translate("AppInfoDialog", "Vietnamese", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(68, QtGui.QApplication.translate("AppInfoDialog", "Welsh", None, QtGui.QApplication.UnicodeUTF8))
        self.Language.setItemText(69, QtGui.QApplication.translate("AppInfoDialog", "Yoruba", None, QtGui.QApplication.UnicodeUTF8))
        self.TrademarksLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Trademarks", None, QtGui.QApplication.UnicodeUTF8))
        self.VersionGroupBox.setTitle(QtGui.QApplication.translate("AppInfoDialog", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.DisplayVersionLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Display version", None, QtGui.QApplication.UnicodeUTF8))
        self.DisplayVersionType.setItemText(0, QtGui.QApplication.translate("AppInfoDialog", "Development Test", None, QtGui.QApplication.UnicodeUTF8))
        self.DisplayVersionType.setItemText(1, QtGui.QApplication.translate("AppInfoDialog", "Pre-Release", None, QtGui.QApplication.UnicodeUTF8))
        self.DisplayVersionType.setItemText(2, QtGui.QApplication.translate("AppInfoDialog", "(official release)", None, QtGui.QApplication.UnicodeUTF8))
        self.DisplayVersionType.setItemText(3, QtGui.QApplication.translate("AppInfoDialog", "Revision", None, QtGui.QApplication.UnicodeUTF8))
        self.PackageVersionLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Package version", None, QtGui.QApplication.UnicodeUTF8))
        self.PackageVersion.setInputMask(QtGui.QApplication.translate("AppInfoDialog", "000.000.000.000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.LicenseGroupBox.setTitle(QtGui.QApplication.translate("AppInfoDialog", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.Shareable.setText(QtGui.QApplication.translate("AppInfoDialog", "Shareable", None, QtGui.QApplication.UnicodeUTF8))
        self.OpenSource.setText(QtGui.QApplication.translate("AppInfoDialog", "Open source", None, QtGui.QApplication.UnicodeUTF8))
        self.Freeware.setText(QtGui.QApplication.translate("AppInfoDialog", "Freeware", None, QtGui.QApplication.UnicodeUTF8))
        self.CommercialUse.setText(QtGui.QApplication.translate("AppInfoDialog", "Commercial use", None, QtGui.QApplication.UnicodeUTF8))
        self.AdvancedGroupBox.setTitle(QtGui.QApplication.translate("AppInfoDialog", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.PluginsPathLabel.setText(QtGui.QApplication.translate("AppInfoDialog", "Plugins path", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AppInfoDialog", "Requires .NET version", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("AppInfoDialog", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("AppInfoDialog", "1.1", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("AppInfoDialog", "2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("AppInfoDialog", "3.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("AppInfoDialog", "3.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("AppInfoDialog", "4.0", None, QtGui.QApplication.UnicodeUTF8))
        self.UsesJava.setText(QtGui.QApplication.translate("AppInfoDialog", "Uses Java", None, QtGui.QApplication.UnicodeUTF8))

import graphics_rc
